### ISSUE TITLE
Migrate to Astro

### ISSUE THREAD

**Issue by Fredkiss3** [Fredkiss3/fredkiss.dev#23]
## Task list

- [ ] Migration of the existing code to astro
- [ ] New content writing style with https://keystatic.com/docs/installation-astro and [Astro's content collections](https://docs.astro.build/en/guides/content-collections/) 
   - [ ] check this for auth with github : https://keystatic.com/docs/github-mode#new-environment-variables
   - [ ] customize UI : https://keystatic.com/docs/user-interface#brand
- [ ] Dark mode #17 
- [ ] Blog Layout #5  with custom OG generation using `satori` :  https://github.com/fogbender/b2b-saaskit/tree/main/src/pages/og
